name: everything_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  graphql_flutter: ^1.0.0
  url_launcher: ^3.0.2
  simple_animations: ^1.3.0
  flutter_screen_scaler : ^1.0.0
  scoped_model: ^1.0.1
  get_it: ^1.0.3
  snaplist: ^0.1.8



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: TTCommons
      fonts:
        - asset: assets/fonts/TTCommons-Medium.ttf
        - asset: assets/fonts/TTCommons-Bold.ttf
          weight: 900
        - asset: assets/fonts/TTCommons-Italic.ttf
          style: italic
