name: everything_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_responsive_screen: ^1.0.0
  carousel_slider: ^1.3.0
  graphql_flutter: ^1.0.0
  url_launcher: ^3.0.2
  simple_animations: ^1.3.0
  shared_preferences: ^0.4.3
  flutter_screenutil: ^0.5.2
  flutter_screen_scaler : ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: TTCommons
      fonts:
        - asset: assets/fonts/TTCommons-Medium.ttf
        - asset: assets/fonts/TTCommons-Bold.ttf
          weight: 900
        - asset: assets/fonts/TTCommons-Italic.ttf
          style: italic
